Sometimes data from AmazonS3 is just corrupt and returns with exception. Since the InputStream is passed back to the client then the exception will cause a 406 (NOT_ACCEPTABLE) response in the client. So we will accept 406 as a temporary network problem.
com.amazonaws.AmazonClientException: Unable to verify integrity of data download. Client calculated content hash didn't match hash calculated by Amazon S3. The data may be corrupt.
at com.amazonaws.services.s3.internal.DigestValidationInputStream.validateMD5Digest(DigestValidationInputStream.java:80)
at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:62)
at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
at java.io.InputStream.read(InputStream.java:162)
at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:146)
at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:103)
at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:39)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)